### ISSUE TITLE
RuntimeError: Error: No module named 'Sakura_Poselib-1'

### ISSUE THREAD

**Issue by GDe12** [kafuji/Sakura_Poselib#12]
When I try to instal the addon in blender 4.2 I get this pop up:
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1326, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2386, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2514, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\startup\bl_operators\userpref.py", line 821, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'Sakura_Poselib-1'

**Comment by kafuji** [comment]
blender_manifest.toml (added once to testing purpose) was causing this.
It was removed in recent versions.
Thanks!
